version: "3"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - flask
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./cert:/etc/ssl
  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    container_name: flask
    stop_signal: SIGINT
    restart: always
    expose:
      - 5000